name: Update CurseForge Metadata

on:
  schedule:
    - cron: '0 0 * * MON'   # every Monday at 0:00 UTC
  workflow_dispatch:    # manual trigger

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # so the push can use the token

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetcher script
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CURSEFORGE_PROJECT_IDS: [931047, 928506, 867373, 1116103, 1073608, 876916, 881888, 662863, 1066197]  # needs manual updating cf search doesn't work
        run: |
          python backendScripts/fetchCfInfo.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/mods_metadata.json logos/
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update CurseForge metadata"
            git push
          fi
