name: Update Static Data

on:
  schedule:
    - cron: '0 0 * * MON'   # every Monday at 0:00 UTC
  workflow_dispatch:    # manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # so the push can use the token

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run cf fetcher script
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CURSEFORGE_PROJECT_IDS: "931047,928506,867373,1116103,1073608,876916,881888,662863,1066197"  # needs manual updating cf search doesn't work
        run: |
          python backendScripts/fetchCfInfo.py
      
      - name: Run wago fetcher script
        env:
          WAGO_USER: "Jodsderechte"
        run: |
          python backendScripts/fetchWagoInfo.py

      - name: Run wago categoriesfetcher script
        run: |
          python backendScripts/fetchWagoCategoryInfo.py
          python backendScripts/generateWagoPoFiles.py

      - name: Run linkedin fetcher script
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: |
          python backendScripts/fetchLinkedInInfo.py

      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Jodsderechte
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: regular
          config_octicon: yes
          config_order:   base.header,   introduction,   base.activity+community,   base.repositories,   lines,   followup,   discussions,   notable,   projects,   repositories,   gists,   pagespeed,   habits,   topics,   music,   nightscout,   posts,   rss,   tweets,   isocalendar,   calendar,   stars,   starlists,   stargazers,   people,   activity,   reactions,   skyline,   support,   languages,
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 0
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: ShaderLab, hlsl
          plugin_languages_limit: 10
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: Ateria, UnrealEngine, Ateria_old
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: public
          repositories_affiliations: ""
          config_output: json



      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
           if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update CurseForge metadata"
            git push
          fi
