#Converts Markdown files to html
name: Convert Markdown to HTML
# this should run whenever there is a push in the Addons folder which get's new Readmes from the Addons when they are updated
on:
  push:
     paths:
     - 'Addons/**'
  workflow_dispatch: 
   
jobs:
# converts the file
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  

    # The matrix job should only run 1 at a time to not create Concurrency problems when writing 
    strategy:
      max-parallel: 1
      matrix:
        Addons: [DungeonAuraTools,CustomNames,GroupFinderRio,AutoDoors,CheatDeath]
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          dark-mode: false
          markdown-style-theme: dark
          source: Addons/${{matrix.Addons}}/README.md
          output: Data/${{matrix.Addons}}.html
          
      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
           clean: false
           force: false
           branch: main # Pushes the updates to the main branch.
           folder: Data # The location of the data.json file saved by the Fetch API Data action.
           target-folder: Data # Saves the data into the directory on the main branch.
           commit-message: "updated ${{matrix.Addons}} for newest ReadMe version at ${{ github.event.repository.updated_at}}"    
      
