
# description of this workflow, can be anything you want
name: Convert Markdown to HTML

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pullrequests.
on:
  push:
     paths:
     - 'Addons/**'
  workflow_dispatch: 
   

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "convert" is a job, you can name it anything you want
  convert:

    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"

    # "steps" holds a list of all the steps needed to package and release our AddOn
    strategy:
      max-parallel: 1
      matrix:
        Addons: [DungeonAuraTools,CustomNames]
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          dark-mode: false
          markdown-style-theme: dark
          source: Addons/${{matrix.Addons}}/README.md
          output: Data/${{matrix.Addons}}.html
          
      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
           clean: false
           force: false
           branch: main # Pushes the updates to the main branch.
           folder: Data # The location of the data.json file saved by the Fetch API Data action.
           target-folder: Data # Saves the data into the directory on the main branch.
           commit-message: "converted ${{matrix.Addons}} to html"    
      
